---
- name: Generate config in text for debug
  template:                                                                                                                             
    src: "junos_forwarder_config.j2"
    dest: "./debug_configs/{{ inventory_hostname }}_forwarder_config.txt"
  when: forwarders_remove == False and config_debug == True

- name: Configure Junos DHCP Forwarder
  junos_config:
    lines: "{{ lookup('template', 'junos_forwarder_config.j2').split('\n') }}"
    comment: Create Forwarders
  when: forwarders_remove == False and config_debug == False

- name: Remove Junos Forwarders
  junos_config:
    lines: "{{ lookup('template', 'junos_forwarders_remove.j2').split('\n') }}"
    comment: Remove Forwarders
  when: forwarders_remove == True and config_debug == False
